# Site wide configuration

title:            Carolina Vizcaino - Stepping Out of the Classroom
locale:           en_US
url:              www.cviz.co


# Jekyll configuration

permalink:   pretty
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Carolina Vizcaino
  avatar: bio-pic-small.png
  bio: Just an educator figuring out her place outside of the classroom
  email: cvizcaino2003@yahoo.com
  disqus-shortname: cviz
  twitter: cvizcaino7 #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62307103-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: cviz #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: carolinavizcaino #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
